#!/bin/bash
#PBS -q normal
#PBS -l nodes=1:ppn=16:native
#PBS -l walltime=00:15:00
#PBS -N conway_checkerboard_1
#PBS -o Out/conway_checkerboard_1.out
#PBS -e Log/conway_checkerboard_1.log
#PBS -A TG-CCR120040
#PBS -M gregory.petropoulos@colorado.edu
#PBS -m abe
#PBS -V
# Start of user commands - comments start with a hash sign (#)
cd /oasis/scratch/gregp/temp_project/cs_5576/conway-game-of-life
mpirun -np 9 -hostfile $PBS_NODEFILE ./cgl conway-900x900.pgm checkerboard 10 2 9
